### PR TITLE
fix: upgrade to flutter_form_builder ^6.0.0

### PR DESCRIPTION
**Pull request by Prn-Ice**
Forgot to uncheck some files from version control 🥲

### CODE REVIEW

**Comment by syedecryptr** [comment]
please update this.

**Comment by JorgeEspadas** [comment]
@danvick please merge

**Comment by Shiba-Kar** [comment]
Is there any reason this package is not merged ?

**Comment by YouSour** [comment]
what happen to this package ? any new about this , guy?

**Comment by Shiba-Kar** [comment]
Nice !! . you have left out some commas and save json files as  xxxxxxx.json   From: Simon SymhovenSent: Tuesday, July 13, 2021 11:39 AMTo: danvick/form_builder_phone_fieldCc: Shiba Prasad Kar; CommentSubject: Re: [danvick/form_builder_phone_field] fix: upgrade to flutter_form_builder ^6.0.0 (#6) Great package, love to use this plugin @danvick. Can you please merge this feature cause of #7? That would be great!—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by simonsymhoven** [comment]
> Nice !! . you have left out some commas and save json files as  xxxxxxx.json   From: Simon SymhovenSent: Tuesday, July 13, 2021 11:39 AMTo: danvick/form_builder_phone_fieldCc: Shiba Prasad Kar; CommentSubject: Re: [danvick/form_builder_phone_field] fix: upgrade to flutter_form_builder ^6.0.0 (#6) Great package, love to use this plugin @danvick. Can you please merge this feature cause of #7? That would be great!—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

Sorry?

**Pull request merged**
